#!/bin/bash
# -*- coding: utf-8 -*-
#
# Copyright (c) 2020, Christian E. Hopps
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -ex

docker plugin enable ${IMAGE_NAME} || true
docker network rm testnet || true
docker network create --driver=""${IMAGE_NAME}"" testnet
docker run --rm --name dut1 --network=testnet alpine sleep 60 &
pid=$!
for ((i=0; i<10; i++)); do
    C=$(docker ps -q -f name=dut1)
    if [[ -n "$C" ]]; then
        break
    fi
    sleep 1
done
IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dut1)
docker run --rm --name dut2 --network=testnet alpine ping -c 1 $IP
docker stop -t1 dut1 || true
